kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: service-account-binding
  namespace: hollowteam
subjects:
- kind: User
  name: employee
  apiGroup: ""
- kind: ServiceAccount
  name: hollowteam-user
  namespace: hollowteam
roleRef:
  kind: Role
  name: deployment-manager
  apiGroup: ""