---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hollowteam-full-access
  namespace: hollowteam
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]