---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hollowteam-role-binding
  namespace: hollowteam
subjects:
- kind: ServiceAccount
  name: hollowteam-user
  namespace: hollowteam
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: hollowteam-full-access