apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: burgerstores-admin-edit
rules:
  - apiGroups: ["tutorialworks.com"]
    resources: ["burgerstores"]
    verbs: ["get", "list", "watch", "create",
            "update", "patch", "delete", "deletecollection"]