apiVersion: batch/v1
kind: CronJob
metadata:
    name: kubernetes-cron-job
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: cron-batch-job
        spec:
          restartPolicy: OnFailure
          containers:
          - name: kube-cron-job
            image: docker.io/library/kubernetes-job-demo:dev1
            args: ["15"]
