apiVersion: batch/v1
kind: Job
metadata:
  name: kubernetes-job-example
  labels:
    jobgroup: jobexample
spec:
  template:
    metadata:
      name: kubejob
      labels:
        jobgroup: jobexample
    spec:
      containers:
      - name: c-job
        image: docker.io/library/kubernetes-job-demo:dev1
        args: ["10"]
      restartPolicy: OnFailure
