---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: simple-app
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    simple-app: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: simple-app
spec:
  selector:
    matchLabels:
      simple-app: ""
  template:
    metadata:
      labels:
        simple-app: ""
    spec:
      containers:
      - name: simple-app
        #image: docker.io/dkalinin/k8s-simple-app@sha256:4c8b96d4fffdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0
        #private repositories: failed
        #image: 192499874028.dkr.ecr.us-west-2.amazonaws.com/k8s-simple-app:1.0.0
        #public repositories - passed
        #image: docker.io/dsatya6/k8s-simple-app:1.0.0
        #pubich repo - aws 
        image: public.ecr.aws/satyad-pubic-registry/satyad/apps/k8s-simple-app:1.0.0
        env:
        - name: HELLO_MSG
          #value: image from docker.io/dsatya6/k8s-simple-app:1.0.0
          value: image from modified public.ecr.aws/satyad-pubic-registry/satyad/apps/k8s-simple-app:1.0.0
