#@ load("@ytt:data", "data")

apiVersion: kbld.k14s.io/v1alpha1
kind: Config
sources:
- image: docker.io/dkalinin/k8s-simple-app
  path: .

#@ if/end data.values.push_images_repo:
---
apiVersion: kbld.k14s.io/v1alpha1
kind: Config
destinations:
- image: docker.io/dkalinin/k8s-simple-app
  newImage: #@ data.values.push_images_repo
